### ISSUE TITLE
Problema em contar bytes com PrintWriter

### ISSUE THREAD

**Issue by rogerio-dasilva** [labbsr0x/servlet-monitor#1]
Identifiquei problema na codificação de caracteres quando usa-se PrintWriter, assim criado nova classe CountingPrintWriter.java para contar bytes.

Novas funcionalidades:
- Debug para acompanhar a execução
- Excluir paths nas métricas (separados por vírgula)

Exemplo: web.xml
```xml
    <filter>
        <filter-name>metricsFilter</filter-name>
        <filter-class>br.com.labbs.monitor.filter.MetricsCollectorFilter</filter-class>
        <init-param>
            <param-name>buckets</param-name>
            <param-value>0.01,0.05,0.1,0.5,1,2.5,5,7.5,10</param-value>
        </init-param>
        <init-param>
            <param-name>exclusions</param-name>
            <param-value>/estatico,/seam/resource/graphicImage,/a4j/s/3_3_3.Final,/a4j/g/3_3_3.Final</param-value>
        </init-param>
        <init-param>
            <param-name>debug</param-name>
            <param-value>true</param-value>
        </init-param>
    </filter>
```

[CountingPrintWriter.txt](https://github.com/labbsr0x/servlet-monitor/files/3841897/CountingPrintWriter.txt)
[CountingServletOutputStream.txt](https://github.com/labbsr0x/servlet-monitor/files/3841898/CountingServletOutputStream.txt)
[CountingServletResponse.txt](https://github.com/labbsr0x/servlet-monitor/files/3841899/CountingServletResponse.txt)
[DebugUtil.txt](https://github.com/labbsr0x/servlet-monitor/files/3841900/DebugUtil.txt)
[MetricsCollectorFilter.txt](https://github.com/labbsr0x/servlet-monitor/files/3841903/MetricsCollectorFilter.txt)

**Comment by eabili0** [comment]
@rogerio-dasilva, tudo bom? Poderia por favor abrir um PR com suas alterações?

**Comment by rogerio-dasilva** [comment]
Abílio, segue imagens com o erro e depois com a correção.

O problema ocorria na renderização da Modal do componente <rich:modalPanel> do  RichFaces-3.3.4, onde palavras com acento causava erro no carregamento de xml via ajax do componente, ficando em carregamento infinitamente.

A versão do Jboss Seam do nosso projeto é 2.2.0.FINAL

Erro:

![erro-xml](https://user-images.githubusercontent.com/28370226/69048323-f61ffa00-09db-11ea-89c4-50f201ff3856.png)
