### ISSUE TITLE
Application version as parameter

### ISSUE THREAD

**Issue by hfantin** [labbsr0x/servlet-monitor#27]
Hi, we are using the **servlet-monitor** in our springboot projects where we can't create a new file application.properties to set the application.version property.
So, I was wondering if its possible to pass this property as a parameter, something like that:
```
addInitParameter("application-version", "${buildProperties.version}")
// programmatic version of this:
<init-param>
    <param-name>application-version</param-name>
    <param-value>v0.0.1</param-value>
</init-param>
```
What do you think?

**Comment by hfantin** [comment]
I opened this pull request: [#28](https://github.com/labbsr0x/servlet-monitor/pull/28)

**Comment by gilliardmacedo** [comment]
@tiagostutz I need this fix too. I think I have deploy permissions in this artifact, so can I release 0.1.1?

**Comment by tiagostutz** [comment]
Absolutely, @gilliardmacedo .!

Thanx.!

**Comment by gilliardmacedo** [comment]
Released 
https://oss.sonatype.org/service/local/repositories/releases/content/br/com/labbs/servlet-monitor/0.1.1/servlet-monitor-0.1.1.pom
