### ISSUE TITLE
Limit errorMessage length on metrics endpoint

### ISSUE THREAD

**Issue by flaviostutz** [labbsr0x/servlet-monitor#29]
On some of our deployments we had a problem with large error messages being used to notify errors because the /metrics endpoint starts to generate too much data on its output, specially if there are lots of different messages being tracked.

My proposal is to limit by default the maximum message output length to 50 chars in order to minimize accidental performance bottlenecks.

For example, the client do 

```
req.setAttribute("error-info", "Some error is going on here, so please be patient while we finish our coffee!")
```

In this case the related errorMessage will be "Some error is going on here, so please be patient|"
The ending "|" indicates that the message was truncated.

What do you think?

**Comment by CarlosPanarello** [comment]
Or use a list of strings separated by comma passed by environment. Other solution will be create an interface/Enum as parameter for message error besides string.

**Comment by flaviostutz** [comment]
I didn't get it. Could you please write an example?

**Comment by CarlosPanarello** [comment]
For example create a environment like this 
list_of_errors= keyError1:Error in http request, keyError2:name incorrect , keyError3:invalid data

Then create a class that gets this list and put in some Map to be access with the key parameter.

Or modify they method to add errorMessage to accept only Enum types, this will force to use only strings that will be create at build time.

**Comment by flaviostutz** [comment]
Could you exercise with some examples of messages, config and result, pls?

**Comment by CarlosPanarello** [comment]
Something like this to create a map from a environment
Then we can use this map to get value from key.

```java
 String envs = "keyError1:Error in http request,keyError2:name incorrect,keyError3:invalid data";
        Arrays.stream(envs.split(","))
            .forEach(env -> map.put(env.split(":")[0].trim(), env.split(":" )[1].trim()));

        map.get("keyError1");
```
